---
env_params: &env_params
  CF_USERNAME: {{kpi-validator-cf-username}}
  CF_PASSWORD: {{kpi-validator-cf-password}}
  CF_API: {{kpi-validator-cf-api}}
  PROVIDER_IP: {{kpi-validator-provider-ip}}
  PROVIDER_USERNAME: {{kpi-validator-provider-username}}
  PROVIDER_PASSWORD: {{kpi-validator-provider-password}}

resources:
- name: platform-monitoring
  type: git
  source:
    uri: git@github.com:pivotal-cf/platform-monitoring
    branch: master
    private_key: {{metrix-git-key}}

jobs:
- name: validate-kpis
  plan:
  - get: platform-monitoring
  - task: compare-kpis
    config:
      platform: linux
      image: docker:///pivotalcf/1.7_metrix

      inputs:
      - name: platform-monitoring

      params:
        <<: *env_params

      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -ex
            pushd platform-monitoring/kpi_monitoring
              ./trigger-event-metrics.sh
              ./runValidator.sh
            popd