---
env_params: &env_params
  CF_USERNAME: {{kpi-validator-cf-username}}
  CF_PASSWORD: {{kpi-validator-cf-password}}
  CF_API: {{kpi-validator-cf-api}}
  PROVIDER_IP: {{kpi-validator-provider-ip}}
  PROVIDER_USERNAME: {{kpi-validator-provider-username}}
  PROVIDER_PASSWORD: {{kpi-validator-provider-password}}

resources:
- name: platform-monitoring
  type: git
  source:
    uri: git@github.com:pivotal-cf/platform-monitoring
    branch: master
    private_key: {{metrix-git-key}}
- name: loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator
    branch: master
    private_key: {{metrix-git-key}}
    tag_filter: v77

jobs:
- name: validate-kpis
  plan:
  - get: platform-monitoring
  - get: loggregator
  - task: compare-kpis
    config:
      platform: linux
      image: docker:///pivotalcf/1.7_metrix

      inputs:
      - name: platform-monitoring
      - name: loggregator

      params:
        <<: *env_params

      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -ex

            pushd loggregator/src/tools/logspinner
              cf api  $CF_API --skip-ssl-validation
              cf login -u $CF_USERNAME -p $CF_PASSWORD -o system -s system
              cf delete logspinner -r -f || true
              cf push logspinner
              cf scale -i 50 logspinner
              for i in {1..500}
              do
                 curl -k https://logspinner.apps.prada.gcp.pcf-metrics.com/?delay=1ns\&cycles=10000000
              done
            popd

            pushd platform-monitoring/kpi_monitoring
              ./run_slow_consumer.sh
              ./trigger-event-metrics.sh
              ./runValidator.sh
            popd