---
env_params: &env_params
  CF_USERNAME: {{kpi-validator-cf-username}}
  CF_PASSWORD: {{kpi-validator-cf-password}}
  DOMAIN: {{kpi-validator-domain}}
  PROVIDER_IP: {{kpi-validator-provider-ip}}
  PROVIDER_USERNAME: {{kpi-validator-provider-username}}
  PROVIDER_PASSWORD: {{kpi-validator-provider-password}}
  OPSMANAGER_URL: {{kpi-validator-opsmanager-url}}
  OPSMANAGER_USERNAME: {{kpi-validator-opsmanager-username}}
  OPSMANAGER_LOGIN_PASSWORD: {{kpi-validator-opsmanager-login-password}}
  OPSMANAGER_KEY: {{kpi-validator-opsmanager-key}}
  RUN_TIME_MINUTES: {{kpi-validator-run-time-minutes}}

resources:
- name: platform-monitoring
  type: git
  source:
    uri: git@github.com:pivotal-cf/platform-monitoring
    branch: master
    private_key: {{metrix-git-key}}
- name: deployments-metrics
  type: git
  source:
    uri: git@github.com:pivotal-cf/deployments-metrics
    branch: master
    private_key: {{metrix-git-key}}
- name: loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator
    branch: master
    private_key: {{metrix-git-key}}
    tag_filter: v77
- name: slack-alert-missing-kpis
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
jobs:
- name: validate-kpis
  plan:
  - get: platform-monitoring
  - get: loggregator
  - get: deployments-metrics
  - task: compare-kpis
    config:
      platform: linux
      image: docker:///pivotalcf/1.7_metrix

      inputs:
      - name: platform-monitoring
      - name: loggregator
      - name: deployments-metrics

      outputs:
      - name: results
        path: ""

      params:
        <<: *env_params

      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -ex
            chmod 600 $OPSMANAGER_KEY
            export OPSMANAGER_KEYPATH=$PWD/$OPSMANAGER_KEY

            cf api  https://api.sys.$DOMAIN --skip-ssl-validation
            cf login -u $CF_USERNAME -p $CF_PASSWORD -o system -s system
            cf delete logspinner -r -f || true
            cf create-user-provided-service kpi-cups -l syslog://pcf.$DOMAIN:12345 || true

            #Commenting out because failedStagingRequests is no longer a metric
            #cf create-quota QUOTA -m 50GB -i -1 || true
            #cf push test-app -p platform-monitoring/kpi_monitoring/assets/test-app.jar -m 50GB || true
            #cf delete test-app -f

            cf push 500-error -p platform-monitoring/kpi_monitoring/assets/500-error.jar
            cf push bad-gateway -p platform-monitoring/kpi_monitoring/assets/bad-gateway.jar
            curl http://500-error.apps.$DOMAIN/greeting
            curl http://bad-gateway.apps.$DOMAIN/greeting
            cf delete 500-error
            cf delete bad-gateway

            cf delete-orphaned-routes -f

            cd loggregator/src/tools/logspinner
              cf push logspinner
              cf scale -i 50 logspinner
              cf bind-service logspinner kpi-cups || true
              cf restage logspinner
              siege -c 50 -t 10s https://logspinner.apps.$DOMAIN/?delay=1ns\&cycles=10000000
            cd -

            pushd platform-monitoring/kpi_monitoring
              set +e
              ./runValidator.sh
              export exitStatus=`echo $?`
            popd

            mv platform-monitoring/kpi_monitoring/missing_kpis results
            #BOSH DEPLOYMENT COMMANDS, NOT OM
            #bosh -n --ca-cert /var/tempest/workspaces/default/root_ca_certificate target 10.0.0.5
            #bosh cleanup --all
            #bosh releases | grep 'cf ' | awk '{ print $4 }' | sed 's/\*//g' > results/cf_version
            gem install cf-uaac
            uaac target https://pcf.$DOMAIN/uaa --skip-ssl-validation
            uaac token owner get opsman admin -s "" -p $OPSMANAGER_LOGIN_PASSWORD
            UAA_ACCESS_TOKEN=`uaac context | grep access_token | sed 's/      access_token: //g'`
            curl -v -k https://pcf.$DOMAIN/api/v0/available_products \
            -X GET \
            -H "Authorization: Bearer $UAA_ACCESS_TOKEN"| jq .[0].product_version | sed 's/\"//g' > results/cf_version

            cf unbind-service logspinner kpi-cups
            cf delete-service kpi-cups -f
            cf delete logspinner -r -f
            exit $exitStatus

    on_failure:
      put: slack-alert-missing-kpis
      inputs:
      - name: results
      params:
        text: "There are missing KPIs in CF $( cat results/cf_version )! \n $( cat results/missing_kpis )"
        username: KPI Bot
