---
env_params: &env_params
  CF_USERNAME: {{kpi-validator-cf-username}}
  CF_PASSWORD: {{kpi-validator-cf-password}}
  CF_API: {{kpi-validator-cf-api}}
  PROVIDER_IP: {{kpi-validator-provider-ip}}
  PROVIDER_USERNAME: {{kpi-validator-provider-username}}
  PROVIDER_PASSWORD: {{kpi-validator-provider-password}}
  OPSMANAGER_URL: {{kpi-validator-opsmanager-url}}
  OPSMANAGER_USERNAME: {{kpi-validator-opsmanager-username}}
  OPSMANAGER_KEY: {{kpi-validator-opsmanager-key}}

resources:
- name: platform-monitoring
  type: git
  source:
    uri: git@github.com:pivotal-cf/platform-monitoring
    branch: master
    private_key: {{metrix-git-key}}
- name: deployments-metrics
  type: git
  source:
    uri: git@github.com:pivotal-cf/deployments-metrics
    branch: master
    private_key: {{metrix-git-key}}
- name: loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator
    branch: master
    private_key: {{metrix-git-key}}
    tag_filter: v77

jobs:
- name: validate-kpis
  plan:
  - get: platform-monitoring
  - get: loggregator
  - get: deployments-metrics
  - task: compare-kpis
    config:
      platform: linux
      image: docker:///pivotalcf/1.7_metrix

      inputs:
      - name: platform-monitoring
      - name: loggregator
      - name: deployments-metrics

      params:
        <<: *env_params

      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -ex
            cf api  $CF_API --skip-ssl-validation
            cf login -u $CF_USERNAME -p $CF_PASSWORD -o system -s system
            cf delete logspinner -r -f

            chmod 600 $OPSMANAGER_KEY
            export OPSMANAGER_KEYPATH=$PWD/$OPSMANAGER_KEY
            pushd platform-monitoring/kpi_monitoring
              ./trigger-event-metrics.sh
            popd

            pushd loggregator/src/tools/logspinner
              cf api  $CF_API --skip-ssl-validation
              cf login -u $CF_USERNAME -p $CF_PASSWORD -o system -s system
              cf push logspinner
              cf scale -i 50 logspinner
              for i in {1..500}
              do
                 curl -k https://logspinner.apps.prada.gcp.pcf-metrics.com/?delay=1ns\&cycles=10000000
              done
            popd

            pushd platform-monitoring/kpi_monitoring
              ./run_slow_consumer.sh
              ./run_slow_netcat.sh
              set +e
              ./runValidator.sh
              export exitStatus=`echo $?`

              cf delete logspinner -r -f
              ./run_kill_netcat.sh
              exit($exitStatus)
            popd

